# Generated by Django 5.2.8 on 2025-11-24 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True, verbose_name='OPIS Truckstop ID')),
                ('name', models.CharField(max_length=255, verbose_name='Truckstop Name')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(verbose_name='Rack ID')),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Retail Price')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['retail_price'], name='api_fuelsta_retail__926c06_idx')],
            },
        ),
    ]
